import {THREE,U,clamp,smooth,height,wave,updateWetness} from './core.js';
import {buildTerrain,buildGrotto,inside,updateRockContacts} from './terrain.js';
import {buildPlants} from './plants.js';
import {buildCamper} from './camper.js';
import {buildWater} from './water.js';
import {buildLife} from './life.js';
import {buildDolphins} from './dolphins.js';
import {batchStatics,inheritedRole} from './optimize.js';
import {buildSplash} from './splash.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {screenUV,mix,color,smoothstep,uniform,float,vec3,positionWorld,pmremTexture} from 'three/tsl';

const $=id=>document.getElementById(id),query=new URLSearchParams(location.search);
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const state={time:Math.max(0,Number(query.get("at"))||0),night:0,nightTarget:0,tide:0,tideTarget:0,breeze:.35,paused:reduced,auto:false,view:'cove',quality:'auto',frames:[],ready:false,errors:[],ripples:0,doorOpen:false,backend:'',dpr:1,autoQualityReduced:false,frameStats:{count:0,sum:0,max:0,slow:0}};
window.addEventListener('error',e=>state.errors.push(e.message));window.addEventListener('unhandledrejection',e=>state.errors.push(String(e.reason)));
const scene=new THREE.Scene();
const camera=new THREE.PerspectiveCamera(innerWidth/innerHeight<.65?47:33,innerWidth/innerHeight,.1,100);camera.position.set(11.88,10.85,19.95);
let renderer,controls,water,camper,life,dolphins,splashes,grotto,plants,frame=0,rippleCursor=0,last=performance.now(),transition=null;
U.time.value=state.time;
const pointer=new THREE.Vector2(),raycaster=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();let pointerDown=null,activePointers=0;
function errorDisplay(error){console.error(error);$('startup').hidden=false;$('startup').classList.add('error');$('startup').innerHTML='';const text=document.createElement('span');text.textContent='The cove could not open on this graphics device.';const retry=document.createElement('button');retry.textContent='Try WebGL 2';retry.onclick=()=>{const url=new URL(location.href);url.searchParams.set('renderer','webgl');location.href=url.href};$('startup').append(text,retry);}
function environmentTexture(night=false){const w=256,h=128,data=new Float32Array(w*h*4);const top=new THREE.Color(night?'#263859':'#a7d6e1'),horizon=new THREE.Color(night?'#6e7e9d':'#e5ead9'),ground=new THREE.Color(night?'#354858':'#8b9f9a');for(let y=0;y<h;y++)for(let x=0;x<w;x++){const v=y/(h-1),a=x/w*Math.PI*2;const c=v<.5?top.clone().lerp(horizon,Math.pow(v*2,.7)):horizon.clone().lerp(ground,smooth(.5,1,v));const sun=Math.exp(-((x/w-.72)**2*800+(v-.28)**2*1000))*(night?.05:4);const i=(y*w+x)*4;data[i]=c.r+sun;data[i+1]=c.g+sun*.89;data[i+2]=c.b+sun*.68;data[i+3]=1;}const tx=new THREE.DataTexture(data,w,h,THREE.RGBAFormat,THREE.FloatType);tx.mapping=THREE.EquirectangularReflectionMapping;tx.needsUpdate=true;return tx;}
const presets={cove:{pos:[11.88,10.85,19.95],target:[0,.89,.05]},camp:{pos:[5.0,5.3,10.8],target:[-2.08,1.53,-1.95]},reef:{pos:[1.1,.1,12.9],target:[.35,-.15,.65]}};
function presetValues(view){const p=presets[view],target=new THREE.Vector3(...p.target),pos=new THREE.Vector3(...p.pos),aspect=innerWidth/innerHeight;if(aspect<.65){if(view==='cove'){pos.set(24.6,16.1,12.7);target.set(0,.65,.10);}else pos.sub(target).multiplyScalar(view==='camp'?1.12:1.55).add(target);}else if(view==='cove'&&aspect<1.05){pos.sub(target).multiplyScalar(1.05/aspect).add(target);}return {pos,target};}
function setView(view,instant=false){state.view=view;$('view').value=view;state.auto=false;controls.autoRotate=false;$('orbit').setAttribute('aria-pressed','false');const v=presetValues(view);if(instant){camera.position.copy(v.pos);controls.target.copy(v.target);controls.update();transition=null;}else transition={start:performance.now(),fromPos:camera.position.clone(),fromTarget:controls.target.clone(),...v,duration:reduced?120:650};}
function setNight(value){state.nightTarget=value;$('day').setAttribute('aria-pressed',value===0);$('dusk').setAttribute('aria-pressed',value===1);document.body.classList.toggle('night',value>.5);}
function setDoor(value=!state.doorOpen){state.doorOpen=value;$('door').setAttribute('aria-pressed',value);camper.doorTarget=value?Math.PI*.56:0;}
function setPaused(value){state.paused=value;$('pause').setAttribute('aria-pressed',value);$('pause').textContent=value?'Resume':'Pause';}
function toggleUI(){const hide=!$('dock').hidden;$('dock').hidden=hide;$('restore').hidden=!hide;if(document.activeElement?.id==='world'||document.activeElement===renderer.domElement)renderer.domElement.focus();else if(hide)$('restore').focus();else $('hide').focus();}
function quality(value){state.quality=value;$('quality').value=value;state.dpr=Math.min(devicePixelRatio,value==='low'?1:value==='high'?1.8:1.5);if(innerWidth<650&&value==='auto')state.dpr=Math.min(devicePixelRatio,1.35);renderer.setPixelRatio(state.dpr);water.reflection.reflector.resolutionScale=value==='low'?.30:.5;}
function addRipple(x,z){if(!inside(x,z)||height(x,z)>U.tide.value-.07)return false;const i=rippleCursor++%U.ripples.length;U.ripples[i].value.set(x,z,state.time,1);state.ripples++;return true;}
function resize(){camera.aspect=innerWidth/innerHeight;camera.fov=camera.aspect<.65?47:33;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(state.ready&&state.view==='cove')setView('cove',true);}
function pointerCoordinates(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);}
function bindUI(){
 $('jump').onclick=()=>{if(dolphins.jumpBoth())setPaused(false);};
 $('day').onclick=()=>setNight(0);$('dusk').onclick=()=>setNight(1);$('tide').oninput=e=>{state.tideTarget=(+e.target.value-45)/100*.40;};$('breeze').oninput=e=>{state.breeze=+e.target.value/100;};$('view').onchange=e=>setView(e.target.value);$('quality').onchange=e=>quality(e.target.value);$('more').onclick=()=>{const expanded=$('secondary').hidden;$('secondary').hidden=!expanded;$('more').setAttribute('aria-expanded',expanded);};$('hide').onclick=toggleUI;$('restore').onclick=toggleUI;$('door').onclick=()=>setDoor();$('pause').onclick=()=>setPaused(!state.paused);$('orbit').onclick=()=>{state.auto=!state.auto;controls.autoRotate=state.auto;transition=null;$('orbit').setAttribute('aria-pressed',state.auto);};
 controls.addEventListener('start',()=>{transition=null;state.auto=false;controls.autoRotate=false;$('orbit').setAttribute('aria-pressed','false');});
 renderer.domElement.addEventListener('pointerdown',e=>{activePointers++;pointerDown=activePointers===1?{x:e.clientX,y:e.clientY,time:performance.now(),id:e.pointerId}:null;});
 renderer.domElement.addEventListener('pointermove',e=>{if(pointerDown&&Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)>5)pointerDown=null;});
 renderer.domElement.addEventListener('pointerup',e=>{activePointers=Math.max(0,activePointers-1);if(!pointerDown||pointerDown.id!==e.pointerId)return;const down=pointerDown;pointerDown=null;if(performance.now()-down.time>550)return;pointerCoordinates(e);const visible=raycaster.intersectObjects(scene.children,true).find(h=>{let p=h.object;while(p){if(!p.visible||p.userData.noPick||p===water.group)return false;p=p.parent;}return h.object.material?.opacity!==0;});
  plane.constant=-U.tide.value;let waterDistance=Infinity;if(raycaster.ray.intersectPlane(plane,hit)){for(let k=0;k<4;k++){plane.constant=-wave(hit.x,hit.z,state.time);raycaster.ray.intersectPlane(plane,hit);}if(inside(hit.x,hit.z)&&height(hit.x,hit.z)<hit.y-.008)waterDistance=raycaster.ray.origin.distanceTo(hit);}
  if(visible&&visible.distance<waterDistance+.025){if(inheritedRole(visible.object)==='camper')setDoor();return;}if(Number.isFinite(waterDistance))addRipple(hit.x,hit.z);});
 renderer.domElement.addEventListener('pointercancel',()=>{activePointers=0;pointerDown=null;});
 window.addEventListener('keydown',e=>{if(e.code!=='Escape'&&(/INPUT|SELECT|TEXTAREA|BUTTON|A/.test(document.activeElement.tagName)||document.activeElement.isContentEditable))return;if(e.code==='KeyH'){e.preventDefault();toggleUI();renderer.domElement.focus();}if(e.code==='KeyJ'){if(dolphins.jumpBoth())setPaused(false);}if(e.code==='KeyD')setNight(state.nightTarget?0:1);if(e.code==='Space'){e.preventDefault();setPaused(!state.paused);}if(e.code==='Digit1')setView('cove');if(e.code==='Digit2')setView('camp');if(e.code==='Digit3')setView('reef');if(e.code==='Escape'&&!$('secondary').hidden){$('secondary').hidden=true;$('more').setAttribute('aria-expanded','false');$('more').focus();}});
 document.addEventListener('visibilitychange',()=>{last=performance.now();});window.addEventListener('resize',resize);
}
// Merge static surfaces by material without touching doors, animals, or their pivots.
async function init(){
 renderer=new THREE.WebGPURenderer({antialias:true,alpha:false,powerPreference:'high-performance',forceWebGL:query.get('renderer')==='webgl'});await renderer.init();state.backend=renderer.backend.isWebGPUBackend?'WebGPU':'WebGL 2';
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;
 $('world').append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Coastal diorama. Drag to orbit, scroll to zoom.');
 const dayTop=color('#a8d0dd'),dayBottom=color('#eff0e7'),nightTop=color('#293d61'),nightBottom=color('#74849c');scene.backgroundNode=mix(mix(dayTop,dayBottom,smoothstep(0,1,screenUV.y)),mix(nightTop,nightBottom,smoothstep(0,1,screenUV.y)),U.night);
 const env=environmentTexture();const pmrem=new THREE.PMREMGenerator(renderer);const environment=pmrem.fromEquirectangular(env);const nightEnvironment=pmrem.fromEquirectangular(environmentTexture(true));scene.environmentNode=mix(pmremTexture(environment.texture),pmremTexture(nightEnvironment.texture),U.night);scene.environmentIntensity=.25;
 const sun=new THREE.DirectionalLight('#fff1d9',3.05);sun.position.set(-7,10,-9);sun.castShadow=true;sun.shadow.autoUpdate=false;sun.shadow.needsUpdate=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=9;sun.shadow.camera.bottom=-9;sun.shadow.camera.near=.5;sun.shadow.camera.far=28;sun.shadow.bias=-.00035;sun.shadow.normalBias=.023;sun.shadow.radius=3.2;scene.add(sun);U.sun.value.copy(sun.position).normalize();
 const fill=new THREE.HemisphereLight('#c1dce7','#9b8c72',.60);scene.add(fill);const rim=new THREE.DirectionalLight('#cadfeb',.30);rim.position.set(-4,3,6);scene.add(rim);
 buildTerrain(scene);grotto=buildGrotto(scene);plants=buildPlants(scene);camper=buildCamper(scene);camper.group.traverse(m=>{if(m.isMesh)m.layers.enable(2);});camper.interiorLight.shadow.camera.layers.set(2);life=buildLife(scene);splashes=buildSplash(scene);dolphins=buildDolphins(scene,(x,z,strength,eventTime=state.time,velocity)=>{splashes.emit(x,z,strength,eventTime,velocity);const r=U.ripples[rippleCursor++%U.ripples.length];r.value.set(x,z,eventTime,strength*1.5);if(strength>.6&&velocity){const direction=velocity.clone().setY(0).normalize();for(let i=1;i<=2;i++){U.ripples[rippleCursor++%U.ripples.length].value.set(x-direction.x*i*.22,z-direction.z*i*.22,eventTime+i*.11,.60/i);}}});batchStatics(scene);water=buildWater(scene);
 controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.enablePan=false;controls.minDistance=8.5;controls.maxDistance=39;controls.minPolarAngle=.33;controls.maxPolarAngle=Math.PI*.515;controls.rotateSpeed=.6;controls.zoomSpeed=.75;controls.autoRotateSpeed=.22;controls.target.set(0,1.05,0);
 setView(query.get('view')||'cove',true);if(query.has('night')){state.night=state.nightTarget=U.night.value=1;setNight(1);}if(query.has('tide')){state.tideTarget=U.tide.value=clamp(Number(query.get('tide')),-.18,.22);$('tide').value=45+state.tideTarget/.004;}if(query.has('az')){const a=Number(query.get('az'));camera.position.set(Math.sin(a)*21.7,10.2,Math.cos(a)*21.7);controls.update();}quality('auto');setPaused(reduced||query.has("pause"));bindUI();if(query.has("jump"))dolphins.jumpBoth();dolphins.update(state.time);life.update(state.time,dolphins.dolphins);splashes.update(state.time);
 updateWetness(state.time,0,true);updateRockContacts(U.tide.value,true);scene.updateMatrixWorld(true);water.renderReflection(renderer,camera);await renderer.compileAsync(scene,camera);water.renderReflection(renderer,camera);renderer.render(scene,camera);$('startup').hidden=true;state.ready=true;if(performance.getEntriesByName('cove-start').length)performance.measure('cove-ready','cove-start');
 const metrics=()=>({ready:state.ready,passes:water.profile,startupMs:performance.getEntriesByName('cove-ready')[0]?.duration,revision:THREE.REVISION,backend:state.backend,view:state.view,night:state.night,tide:U.tide.value,paused:state.paused,doorOpen:state.doorOpen,doorAngle:camper.hinge.rotation.y,ripples:state.ripples,dpr:state.dpr,drawCalls:renderer.info.render.drawCalls,slowFrames:state.frames.filter(v=>v>50).length,maxFrameMs:Math.max(0,...state.frames),allFrames:{count:state.frameStats.count,fps:state.frameStats.count*1000/state.frameStats.sum,maxMs:state.frameStats.max,over50ms:state.frameStats.slow},p95FrameMs:[...state.frames].sort((a,b)=>a-b)[Math.floor(state.frames.length*.95)]||0,triangles:renderer.info.render.triangles,frame:frame,fps:state.frames.length?1000/(state.frames.reduce((a,b)=>a+b,0)/state.frames.length):0,camera:camera.position.toArray(),target:controls.target.toArray(),viewport:[innerWidth,innerHeight],errors:state.errors,school:life.info(),dolphins:dolphins.info(),splash:splashes.info(),autoQualityReduced:state.autoQualityReduced});
 window.tideglass={state,scene,camera,controls,renderer,water,camper,plants,grotto,life,metrics,setView,setNight,setDoor,setPaused,addRipple,setTide:v=>{state.tideTarget=clamp(v,-.18,.22);$('tide').value=45+state.tideTarget/.004;},orbitTo:a=>{transition=null;state.auto=false;controls.autoRotate=false;const radius=24.5;camera.position.set(Math.sin(a)*radius,9,Math.cos(a)*radius);controls.target.set(0,1,0);controls.update();},snapshot:()=>renderer.domElement.toDataURL('image/png')};
 let slow=0;
 function animate(now){
  const raw=now-last;const dt=Math.min(.05,raw/1000);last=now;frame++;
  if(!document.hidden){state.frameStats.count++;state.frameStats.sum+=raw;state.frameStats.max=Math.max(state.frameStats.max,raw);if(raw>50)state.frameStats.slow++;state.frames.push(raw);if(state.frames.length>600)state.frames.shift();if(!state.paused)state.time+=dt;}
  const smoothing=1-Math.exp(-dt*4);state.night+=(state.nightTarget-state.night)*smoothing;U.night.value=state.night;U.time.value=state.time;U.breeze.value+=(state.breeze-U.breeze.value)*smoothing;U.tide.value+=(state.tideTarget-U.tide.value)*(1-Math.exp(-dt*3));
  updateWetness(state.time,dt);updateRockContacts(U.tide.value);
  sun.color.set('#fff1d9').lerp(new THREE.Color('#b6caec'),state.night);sun.intensity=3.05*(1-state.night)+.26*state.night;fill.intensity=.60*(1-state.night)+.48*state.night;fill.color.set('#d2edf2').lerp(new THREE.Color('#99afe7'),state.night);rim.intensity=.30*(1-state.night)+.38*state.night;scene.environmentIntensity=.25*(1-state.night)+.20*state.night;renderer.toneMappingExposure=1.03*(1-state.night)+1.10*state.night;
  const breath=.5+.5*Math.sin(state.time*1.05+.4);grotto.light.intensity=(.045+breath*.025)*(1-state.night)+(.16+breath*.035)*state.night;grotto.light.position.y=.3+U.tide.value*.5;
  camper.hinge.rotation.y+=(camper.doorTarget-camper.hinge.rotation.y)*(1-Math.exp(-dt*6));camper.interiorLight.intensity=(state.doorOpen?.18:0)+state.night*.65;if(Math.abs(camper.hinge.rotation.y-camper.doorTarget)>.006)camper.interiorLight.shadow.needsUpdate=frame%3===0;camper.lanternLight.intensity=state.night*.65;camper.glow.emissiveIntensity=.08+state.night*2.8;camper.ceiling.emissiveIntensity=.10+state.night*1.5;
  dolphins.update(state.time);life.update(state.time,dolphins.dolphins);splashes.update(state.time);$('jump').disabled=!dolphins.canJump();water.reflection.target.position.y=U.tide.value;
  if(transition){const k=clamp((now-transition.start)/transition.duration),s=k*k*(3-2*k);camera.position.lerpVectors(transition.fromPos,transition.pos,s);controls.target.lerpVectors(transition.fromTarget,transition.target,s);if(k===1)transition=null;}
  controls.autoRotate=state.auto&&!state.paused;controls.update(dt);
  try{sun.shadow.needsUpdate=frame===1||((!state.paused||Math.abs(camper.hinge.rotation.y-camper.doorTarget)>.006)&&frame%3===0);water.renderReflection(renderer,camera,frame%2===0);renderer.render(scene,camera);}catch(e){state.errors.push(String(e));renderer.setAnimationLoop(null);errorDisplay(e);return;}
  if(frame%30===0)document.body.dataset.metrics=JSON.stringify(metrics());
  if(frame>240&&frame%240===0&&state.quality==='auto'&&!state.autoQualityReduced){const avg=state.frames.reduce((a,b)=>a+b,0)/state.frames.length;if(avg>25)slow++;else slow=0;if(slow>=2){state.autoQualityReduced=true;state.dpr=Math.max(.9,state.dpr*.78);renderer.setPixelRatio(state.dpr);water.reflection.reflector.resolutionScale=.32;}}
 }
 last=performance.now();renderer.setAnimationLoop(animate);
}
init().catch(errorDisplay);
